# Mix Fase 1 (Uni√≥n conjunto de Datos) y Fase 2 (Limpieza de Datos)

## Union Data Frames

## Importamos las librerias que necesitemos

In [56]:
import sys

sys.path.append('../')

from src import support_dataframes as sup_df
import pandas as pd
pd.set_option('display.max_columns', False)

## Declaramos nuestros dataframes

In [57]:
df_2013 = pd.read_csv('../datos/datos-2013.csv', sep=';')
df_2014 = pd.read_csv('../datos/datos-2014.csv', sep=';')
df_2015 = pd.read_csv('../datos/datos-2015.csv', sep=';')
df_2016 = pd.read_csv('../datos/datos-2016.csv', sep=';')
df_2017 = pd.read_csv('../datos/datos-2017.csv', sep=';')
df_2018 = pd.read_csv('../datos/datos-2018.csv', sep=';')
df_2019 = pd.read_csv('../datos/datos-2019.csv', sep=';')
df_2020 = pd.read_csv('../datos/datos-2020.csv', sep=';')
df_2021 = pd.read_csv('../datos/datos-2021.csv', sep=';')

lista_dataframes = [df_2013, df_2014, df_2015, df_2016, df_2017, df_2018, df_2019, df_2020, df_2021]

### Limpiamos los nombres de las columnas a minuscula

In [58]:
for df in lista_dataframes:
    df.columns = sup_df.limpiar_lista_palabras(df.columns)

## Rellenamos los anios con valores nulos ya que sabemos a que anio pertenecen

In [59]:
anios = [int(i) for i in range(2013, 2022)]
for i, df in enumerate(lista_dataframes):
    df['ano_exercicio'].fillna(anios[i], inplace=True);
    df['ano_exercicio'] = df['ano_exercicio'].astype(int);

C:\Users\JLFA\AppData\Local\Temp\ipykernel_2368\1235319678.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['ano_exercicio'].fillna(anios[i], inplace=True);
C:\Users\JLFA\AppData\Local\Temp\ipykernel_2368\1235319678.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['ano_exercicio'].fillna(anios[i], inplace=True);
C:\Users\JLFA\AppData\Local\Temp\ipykernel_2368\1235319678.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['ano_exercicio'].fillna(anios[i], inplace=True);
C:\Users\JLFA\AppData\Local\Temp\ipykernel_2368\1235319678.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['ano_exercicio'].fillna(anios[i], inplace=True);
C:\Users\JLFA\AppData\Local\Temp\ipykernel_2368\1235319678.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['ano_exercicio'].fillna(anios[i], inplace=True);
C:\Users\JLFA\AppData\Local\Temp\ipykernel_2368\1235319678.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['ano_exercicio'].fillna(anios[i], inplace=True);
C:\Users\JLFA\AppData\Local\Temp\ipykernel_2368\1235319678.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['ano_exercicio'].fillna(anios[i], inplace=True);
C:\Users\JLFA\AppData\Local\Temp\ipykernel_2368\1235319678.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['ano_exercicio'].fillna(anios[i], inplace=True);
C:\Users\JLFA\AppData\Local\Temp\ipykernel_2368\1235319678.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['ano_exercicio'].fillna(anios[i], inplace=True);

## Concatenamos los DataFrame

In [60]:
dfs_concatenados = pd.concat(lista_dataframes)

print(dfs_concatenados.shape)
dfs_concatenados.sample(5)

(1026299, 16)

        codigo_orgao_superior  ... ano_exercicio
115901                26000.0  ...          2019
35045                 52000.0  ...          2017
128429                32000.0  ...          2020
65571                 25000.0  ...          2016
114555                26000.0  ...          2018

[5 rows x 16 columns]

## Intentamos rellenar la celda 'nome_orgao_superior' a traves del 'codigo_orgao_superior'

### primero, tratamos los nulos con el valor 999999

In [61]:
dfs_concatenados['codigo_orgao_superior'].fillna(999999, inplace=True)

#? cambiamos la columna a tipo int
dfs_concatenados['codigo_orgao_superior'] = dfs_concatenados['codigo_orgao_superior'].astype(int)

codigos_orgao_superior = dfs_concatenados['codigo_orgao_superior'].unique()
codigos_orgao_superior

C:\Users\JLFA\AppData\Local\Temp\ipykernel_2368\911384637.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dfs_concatenados['codigo_orgao_superior'].fillna(999999, inplace=True)

array([ 63000,  37000, 999999,  22000,  55000,  24000,  52000,  25000,
        26000,  39000,  30000,  81000,  58000,  33000,  36000,  41000,
        57000,  35000,  32000,  49000,  53000,  51000,  44000,  38000,
        54000,  20000])

### Creamos un diccionario con los codigos y nombres de las orgao superiores

In [62]:
diccionario_codigo_nome_superior = {}

for codigo in codigos_orgao_superior:
    condicion = dfs_concatenados['codigo_orgao'] == codigo
    df_codigo_nome = dfs_concatenados[condicion].filter(like='orgao_superior')
    valores = df_codigo_nome['nome_orgao_superior'].unique()
    nome = valores[pd.notna(valores)]

    if len(nome) > 0:
        diccionario_codigo_nome_superior[int(codigo)] = nome[0]
    else:
        diccionario_codigo_nome_superior[int(codigo)] = 'Desconocido'



diccionario_codigo_nome_superior

{63000: 'Advocacia-Geral da Uni√£o',
 37000: 'Controladoria-Geral da Uni√£o',
 999999: 'Desconocido',
 22000: 'Minist√©rio da Agricultura, Pecu√°ria e Abastec',
 55000: 'Minist√©rio da Cidadania',
 24000: 'Minist√©rio da Ci√™ncia, Tecnologia, Inova√ß√µes ',
 52000: 'Minist√©rio da Defesa',
 25000: 'Minist√©rio da Economia',
 26000: 'Minist√©rio da Educa√ß√£o',
 39000: 'Minist√©rio da Infraestrutura',
 30000: 'Minist√©rio da Justi√ßa e Seguran√ßa P√∫blica',
 81000: 'Minist√©rio da Mulher, Fam√≠lia e Direitos Huma',
 58000: 'Minist√©rio da Pesca e Aquicultura',
 33000: 'Minist√©rio da Previd√™ncia Social',
 36000: 'Minist√©rio da Sa√∫de',
 41000: 'Minist√©rio das Comunica√ß√µes',
 57000: 'Desconocido',
 35000: 'Minist√©rio das Rela√ß√µes Exteriores',
 32000: 'Minist√©rio de Minas e Energia',
 49000: 'Minist√©rio do Desenvolvimento Agr√°rio',
 53000: 'Minist√©rio do Desenvolvimento Regional',
 51000: 'Desconocido',
 44000: 'Minist√©rio do Meio Ambiente',
 38000: 'Minist√©rio do Trabalho e Emprego',
 54000: 'Minist√©rio do Turismo',
 20000: 'Desconocido'}

### Ahora cambiamos los nulos

In [63]:
dfs_concatenados['nome_orgao_superior'] = dfs_concatenados['nome_orgao_superior'].fillna(
    dfs_concatenados['codigo_orgao_superior'].map(diccionario_codigo_nome_superior)
)

condicion = dfs_concatenados['codigo_orgao_superior'] == codigos_orgao_superior[3]
dfs_concatenados[condicion]

      codigo_orgao_superior  ... ano_exercicio
20                    22000  ...          2013
21                    22000  ...          2013
22                    22000  ...          2013
23                    22000  ...          2013
24                    22000  ...          2013
...                     ...  ...           ...
5817                  22000  ...          2021
5818                  22000  ...          2021
5819                  22000  ...          2021
5820                  22000  ...          2021
5821                  22000  ...          2021

[44809 rows x 16 columns]

## Vamos a explorar los nulos que tenemos antes de guardar los datos

In [64]:
porcentaje_nulos = sup_df.mostrar_porcentaje_nulos(dfs_concatenados)
porcentaje_nulos

                      Columna  Porcentaje Nulos
10  valor_previsto_atualizado          5.000005
12            valor_realizado          3.845371
7              origem_receita          3.743354
3                  nome_orgao          3.399302
4      codigo_unidade_gestora          3.272048
8             especie_receita          3.110887
9                detalhamento          2.858524
11              valor_lancado          2.574201
2                codigo_orgao          2.447337
13       percentual_realizado          2.351556
14            data_lancamento          2.322033
5        nome_unidade_gestora          1.898180
6         categoria_economica          1.849169
0       codigo_orgao_superior          0.000000
1         nome_orgao_superior          0.000000
15              ano_exercicio          0.000000

## Ahora limpiamos los nombres de orgao con codigo orgao

In [65]:
dfs_concatenados['codigo_orgao'].fillna(999999, inplace=True)

#? cambiamos la columna a tipo int
dfs_concatenados['codigo_orgao'] = dfs_concatenados['codigo_orgao'].astype(int)

codigos_orgao = dfs_concatenados['codigo_orgao'].unique()
codigos_orgao

C:\Users\JLFA\AppData\Local\Temp\ipykernel_2368\590349420.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dfs_concatenados['codigo_orgao'].fillna(999999, inplace=True)

array([ 63000,  66000,  22202,  22000,  22211, 999999,  44208,  22201,
        22905,  49001,  55000,  55001,  24000,  20501,  20301,  24901,
        20502,  24209,  20402,  49280,  52911,  52904,  52132,  52912,
        52131,  52121,  52111,  31280,  52000,  52133,  52221,  52211,
        52222,  30203,  25000,  37202,  25205,  20603,  25201,  38901,
        25208,  33206,  30204,  25203,  37201,  20202,  25915,  25207,
        25914,  22500,  25901,  25211,  25904,  61201,  28500,  25916,
        20924,  71902,  25905,  26435,  26276,  26000,  26285,  26233,
        26407,  26232,  26405,  26292,  26423,  26422,  26251,  26234,
        26275,  26238,  26261,  26244,  26432,  26414,  26421,  26411,
        26270,  26417,  26410,  26282,  26430,  26258,  26278,  26416,
        26253,  26420,  26418,  26408,  26240,  26246,  26433,  26428,
        26263,  26412,  26404,  26248,  26434,  26409,  26264,  26424,
        26415,  26291,  26413,  26236,  26243,  26255,  26419,  26247,
        26271,  26266,  26402,  26277,  26252,  26351,  26403,  26245,
        26294,  26298,  26425,  26427,  26268,  26429,  26256,  26290,
        26279,  26201,  26257,  26231,  26235,  26260,  26437,  26439,
        26272,  26438,  26262,  26440,  26267,  26254,  26237,  26441,
        26442,  26352,  26230,  26280,  26241,  26350,  26281,  26431,
        26249,  26269,  26436,  26250,  26284,  26426,  26239,  26406,
        26286,  26242,  26273,  26274,  26443,  26283,  62201,  39252,
        39250,  49901,  56901,  39000,  68201,  68000,  39251,  29209,
        62901,  39253,  39816,  39812,  39813,  39811,  39815,  39814,
        39817,  62000,  30802,  30108,  30905,  30907,  30202,  30211,
        30911,  30000,  30912,  30205,  20122,  58000,  33000,  36211,
        36201,  36210,  36000,  36213,  36212,  36208,  36209,  41000,
        20415,  41231,  41232,  41903,  64902,  64901,  35000,  35201,
        20303,  29208,  32000,  32205,  32263,  32210,  32314,  20302,
        49000,  29205,  29214,  53902,  53901,  53903,  22204,  22203,
        53000,  53202,  74917,  56902,  53203,  44205,  53205,  53207,
        74918,  91214,  44206,  44000,  44902,  20701,  44207,  44204,
        38000,  20403,  20604,  42207,  20411,  20412,  34902,  20203,
        54000,  20408,  20404,  54901,  20101,  67000,  64000,  69000,
        20116,  24208,  60000,  20117,  61000,  52233,  37904,  26449,
        26448,  90000,  26447,  26450,  29201,  74919,  20605,  37000,
        20129,  30914,  30913,  81000,  32396,  26456,  26455,  24216,
        26453,  26454,  26457,  26452])

In [66]:
diccionario_codigo_nome = {}

for codigo in codigos_orgao:

    condicion = dfs_concatenados['codigo_orgao'] == codigo
    df_codigo_nome = dfs_concatenados[condicion].filter(regex=r"nome_orgao$")
    valores = df_codigo_nome['nome_orgao'].unique()
    nome = valores[pd.notna(valores)]

    if len(nome) > 0:
        diccionario_codigo_nome[int(codigo)] = nome[0]
    else:
        diccionario_codigo_nome[int(codigo)] = 'Desconocido'

diccionario_codigo_nome

{63000: 'Advocacia-Geral da Uni√£o - Unidades com v√≠nculo direto',
 66000: 'Controladoria-Geral da Uni√£o',
 22202: 'Empresa Brasileira de Pesquisa Agropecu√°ria',
 22000: 'Minist√©rio da Agricultura, Pecu√°ria e Abastecimento - Unidades com v√≠nculo direto',
 22211: 'Companhia Nacional de Abastecimento',
 999999: 'Minist√©rio da Agricultura, Pecu√°ria e Abastecimento - Unidades com v√≠nculo direto',
 44208: 'Servi√ßo Florestal Brasileiro',
 22201: 'Instituto Nacional de Coloniza√ß√£o e Reforma Agr√°ria',
 22905: 'Fundo de Defesa da Economia Cafeeira',
 49001: 'Fundo de Terras e da Reforma Agr√°ria',
 55000: 'Minist√©rio da Cidadania - Unidades com v√≠nculo direto',
 55001: 'Fundo Nacional de Assist√™ncia Social',
 24000: 'Minist√©rio da Ci√™ncia, Tecnologia, Inova√ß√µes e Comunica√ß√µes - Unidades com v√≠nculo direto',
 20501: 'Conselho Nacional de Desenvolvimento Cient√≠fico e Tecnol√≥gico',
 20301: 'Comiss√£o Nacional de Energia Nuclear',
 24901: 'Fundo Nacional de Desenvolvimento Cient√≠fico e Tecnol√≥gico',
 20502: 'Financiadora de Estudos e Projetos',
 24209: 'Centro Nacional de Tecnologia Eletr√¥nica Avan√ßada S.A.',
 20402: 'Ag√™ncia Espacial Brasileira',
 49280: 'Empresa Brasileira de Correios e Tel√©grafos',
 52911: 'Fundo Aeron√°utico',
 52904: 'Fundo do Ex√©rcito',
 52132: 'Comando da Marinha - Fundo Naval',
 52912: 'Fundo Aerovi√°rio',
 52131: 'Comando da Marinha',
 52121: 'Comando do Ex√©rcito',
 52111: 'Comando da Aeron√°utica',
 31280: 'Caixa de Constru√ß√µes de Casas para o Pessoal da Marinha do Brasil',
 52000: 'Minist√©rio da Defesa - Unidades com v√≠nculo direto',
 52133: 'Fundo de Desenvolvimento do Ensino Profissional Mar√≠timo',
 52221: 'Ind√∫stria de Material B√©lico do Brasil',
 52211: 'Caixa de Financiamento Imobili√°rio da Aeron√°utica',
 52222: 'Funda√ß√£o Os√≥rio',
 30203: 'Instituto Nacional de Metrologia, Qualidade e Tecnologia',
 25000: 'Minist√©rio da Economia - Unidades com v√≠nculo direto',
 37202: 'Instituto Nacional do Seguro Social',
 25205: 'Funda√ß√£o Instituto Brasileiro de Geografia e Estat√≠stica',
 20603: 'Superintend√™ncia da Zona Franca de Manaus',
 25201: 'Banco Central do Brasil - Or√ßamento Fiscal e Seguridade Social',
 38901: 'Fundo de Amparo ao Trabalhador',
 25208: 'Superintend√™ncia de Seguros Privados',
 33206: 'Superintend√™ncia Nacional de Previd√™ncia Complementar',
 30204: 'Instituto Nacional da Propriedade Industrial',
 25203: 'Comiss√£o de Valores Mobili√°rios',
 37201: 'Funda√ß√£o Jorge Duprat Figueiredo, de Seguran√ßa e Medicina do Trabalho',
 20202: 'Funda√ß√£o Escola Nacional de Administra√ß√£o P√∫blica',
 25915: 'Fundo Constitucional do Distrito Federal',
 25207: 'Servi√ßo Federal de Processamento de Dados',
 25914: 'Fundo de Garantia √† Exporta√ß√£o',
 22500: 'Companhia de Entrepostos e Armaz√©ns Gerais de S√£o Paulo',
 25901: 'Fundo de Compensa√ß√£o de Varia√ß√µes Salariais',
 25211: 'Casa da Moeda do Brasil',
 25904: 'Fundo de Estabilidade do Seguro Rural',
 61201: 'Instituto de Pesquisa Econ√¥mica Aplicada',
 28500: 'Fundo de Garantia para a Promo√ß√£o da Competitividade',
 25916: 'Fundo Contingente da Extinta RFFSA-FCMP',
 20924: 'Fundo Nacional de Desenvolvimento',
 71902: 'Fundo Soberano do Brasil',
 25905: 'Fundo de Apoio ao Desenvolvimento Social',
 26435: 'Instituto Federal do Rio Grande do Norte',
 26276: 'Funda√ß√£o Universidade Federal do Mato Grosso',
 26000: 'Minist√©rio da Educa√ß√£o - Unidades com v√≠nculo direto',
 26285: 'Funda√ß√£o Universidade Federal de S√£o Jo√£o Del-Rei',
 26233: 'Universidade Federal do Cear√°',
 26407: 'Instituto Federal Goiano',
 26232: 'Universidade Federal da Bahia',
 26405: 'Instituto Federal do Cear√°',
 26292: 'Funda√ß√£o Joaquim Nabuco',
 26423: 'Instituto Federal de Sergipe',
 26422: 'Instituto Federal Catarinense',
 26251: 'Funda√ß√£o Universidade Federal do Tocantins',
 26234: 'Universidade Federal do Esp√≠rito Santo',
 26275: 'Funda√ß√£o Universidade Federal do Acre',
 26238: 'Universidade Federal de Minas Gerais',
 26261: 'Universidade Federal de Itajub√°',
 26244: 'Universidade Federal do Rio Grande do Sul',
 26432: 'Instituto Federal do Paran√°',
 26414: 'Instituto Federal do Mato Grosso',
 26421: 'Instituto Federal de Rond√¥nia',
 26411: 'Instituto Federal do Sudeste de Minas Gerais',
 26270: 'Funda√ß√£o Universidade do Amazonas',
 26417: 'Instituto Federal da Para√≠ba',
 26410: 'Instituto Federal do Norte de Minas Gerais',
 26282: 'Universidade Federal de Vi√ßosa',
 26430: 'Instituto Federal do Sert√£o de Pernambuco',
 26258: 'Universidade Tecnol√≥gica Federal do Paran√°',
 26278: 'Funda√ß√£o Universidade Federal de Pelotas',
 26416: 'Instituto Federal do Par√°',
 26253: 'Universidade Federal Rural da Amaz√¥nia',
 26420: 'Instituto Federal Farroupilha',
 26418: 'Instituto Federal de Pernambuco',
 26408: 'Instituto Federal do Maranh√£o',
 26240: 'Universidade Federal da Para√≠ba',
 26246: 'Universidade Federal de Santa Catarina',
 26433: 'Instituto Federal do Rio de Janeiro',
 26428: 'Instituto Federal de Bras√≠lia',
 26263: 'Universidade Federal de Lavras',
 26412: 'Instituto Federal do Sul de Minas Gerais',
 26404: 'Instituto Federal Baiano',
 26248: 'Universidade Federal Rural de Pernambuco',
 26434: 'Instituto Federal Fluminense',
 26409: 'Instituto Federal de Minas Gerais',
 26264: 'Universidade Federal Rural do Semi-√Årido',
 26424: 'Instituto Federal do Tocantins',
 26415: 'Instituto Federal do Mato Grosso do Sul',
 26291: 'Funda√ß√£o Coordena√ß√£o de Aperfei√ßoamento de Pessoal de N√≠vel Superior',
 26413: 'Instituto Federal do Tri√¢ngulo Mineiro',
 26236: 'Universidade Federal Fluminense',
 26243: 'Universidade Federal do Rio Grande do Norte',
 26255: 'Universidade Federal dos Vales do Jequitinhonha e Mucuri',
 26419: 'Instituto Federal do Rio Grande do Sul',
 26247: 'Universidade Federal de Santa Maria',
 26271: 'Funda√ß√£o Universidade de Bras√≠lia',
 26266: 'Funda√ß√£o Universidade Federal do Pampa',
 26402: 'Instituto Federal de Alagoas',
 26277: 'Universidade Federal de Ouro Preto',
 26252: 'Universidade Federal de Campina Grande',
 26351: 'Universidade Federal do Rec√¥ncavo da Bahia',
 26403: 'Instituto Federal do Amazonas',
 26245: 'Universidade Federal do Rio de Janeiro',
 26294: 'Hospital de Cl√≠nicas de Porto Alegre',
 26298: 'Fundo Nacional de Desenvolvimento da Educa√ß√£o',
 26425: 'Instituto Federal do Acre',
 26427: 'Instituto Federal da Bahia',
 26268: 'Funda√ß√£o Universidade Federal de Rond√¥nia',
 26429: 'Instituto Federal de Educa√ß√£o, Ci√™ncia e Tecnologia de Goi√°s',
 26256: 'Centro Federal de Educa√ß√£o Tecnol√≥gica Celso Suckow da Fonseca',
 26290: 'Instituto Nacional de Estudos e Pesquisas Educacionais An√≠sio Teixeira',
 26279: 'Funda√ß√£o Universidade Federal do Piau√≠',
 26201: 'Col√©gio Pedro II',
 26257: 'Centro Federal de Educa√ß√£o Tecnol√≥gica de Minas Gerais',
 26231: 'Universidade Federal de Alagoas',
 26235: 'Universidade Federal de Goi√°s',
 26260: 'Universidade Federal de Alfenas',
 26437: 'Instituto Federal de Roraima',
 26439: 'Instituto Federal de S√£o Paulo',
 26272: 'Funda√ß√£o Universidade do Maranh√£o',
 26438: 'Instituto Federal de Santa Catarina',
 26262: 'Universidade Federal de S√£o Paulo',
 26440: 'Universidade Federal da Fronteira Sul',
 26267: 'Universidade Federal da Integra√ß√£o Latino-Americana',
 26254: 'Universidade Federal do Tri√¢ngulo Mineiro',
 26237: 'Universidade Federal de Juiz de Fora',
 26441: 'Universidade Federal do Oeste do Par√°',
 26442: 'Universidade da Integra√ß√£o Internacional da Lusofonia Afro-Brasileira',
 26352: 'Funda√ß√£o Universidade Federal do ABC',
 26230: 'Funda√ß√£o Universidade Federal do Vale do S√£o Francisco',
 26280: 'Funda√ß√£o Universidade Federal de S√£o Carlos',
 26241: 'Universidade Federal do Paran√°',
 26350: 'Funda√ß√£o Universidade Federal da Grande Dourados',
 26281: 'Funda√ß√£o Universidade Federal de Sergipe',
 26431: 'Instituto Federal do Piau√≠',
 26249: 'Universidade Federal Rural do Rio de Janeiro',
 26269: 'Universidade Federal do Estado do Rio de Janeiro',
 26436: 'Instituto Federal Sul-rio-grandense',
 26250: 'Universidade Federal de Roraima',
 26284: 'Funda√ß√£o Universidade Federal de Ci√™ncias da Sa√∫de de Porto Alegre',
 26426: 'Instituto Federal do Amap√°',
 26239: 'Universidade Federal do Par√°',
 26406: 'Instituto Federal do Esp√≠rito Santo',
 26286: 'Funda√ß√£o Universidade Federal do Amap√°',
 26242: 'Universidade Federal de Pernambuco',
 26273: 'Universidade Federal do Rio Grande',
 26274: 'Funda√ß√£o Universidade Federal de Uberl√¢ndia',
 26443: 'Empresa Brasileira de Servi√ßos Hospitalares',
 26283: 'Funda√ß√£o Universidade Federal do Mato Grosso do Sul',
 62201: 'Ag√™ncia Nacional de Avia√ß√£o Civil',
 39252: 'Departamento Nacional de Infraestrutura de Transportes',
 39250: 'Ag√™ncia Nacional de Transportes Terrestres',
 49901: 'Departamento do Fundo da Marinha Mercante',
 56901: 'Fundo Nacional de Seguran√ßa e Educa√ß√£o de Tr√¢nsito',
 39000: 'Minist√©rio da Infraestrutura - Unidades com v√≠nculo direto',
 68201: 'Ag√™ncia Nacional de Transportes Aquavi√°rios',
 68000: 'Secretaria de Portos',
 39251: 'Ag√™ncia Nacional de Transportes Aquavi√°rios',
 29209: 'VALEC Engenharia, Constru√ß√µes e Ferrovias S.A.',
 62901: 'Fundo Nacional de Avia√ß√£o Civil',
 39253: 'Empresa de Planejamento e Log√≠stica S.A.',
 39816: 'Companhia Docas do Estado de S√£o Paulo',
 39812: 'Companhia Docas do Estado da Bahia',
 39813: 'Companhia Docas do Cear√°',
 39811: 'Companhia Docas do Rio de Janeiro',
 39815: 'Companhia Docas do Rio Grande do Norte',
 39814: 'Companhia Docas do Par√°',
 39817: 'Companhia Docas do Esp√≠rito Santo',
 62000: 'Secretaria de Avia√ß√£o Civil',
 30802: 'Departamento de Pol√≠cia Rodovi√°ria Federal',
 30108: 'Departamento de Pol√≠cia Federal',
 30905: 'Secretaria Nacional do Consumidor Fundo',
 30907: 'Fundo Penitenci√°rio Nacional',
 30202: 'Funda√ß√£o Nacional do √çndio',
 30211: 'Conselho Administrativo de Defesa Econ√¥mica',
 30911: 'Fundo Nacional de Seguran√ßa P√∫blica',
 30000: 'Minist√©rio da Justi√ßa e Seguran√ßa P√∫blica - Unidades com v√≠nculo direto',
 30912: 'Fundo Nacional Antidrogas',
 30205: 'Funda√ß√£o Nacional do √çndio - Patrim√¥nio Ind√≠gena',
 20122: 'Secretaria Nacional de Pol√≠ticas para Mulheres',
 58000: 'Minist√©rio da Pesca e Aquicultura - Unidades com v√≠nculo direto',
 33000: 'Minist√©rio da Previd√™ncia Social - Unidades com v√≠nculo direto',
 36211: 'Funda√ß√£o Nacional de Sa√∫de',
 36201: 'Funda√ß√£o Oswaldo Cruz',
 36210: 'Hospital Nossa Senhora da Concei√ß√£o S.A.',
 36000: 'Minist√©rio da Sa√∫de - Unidades com v√≠nculo direto',
 36213: 'Ag√™ncia Nacional de Sa√∫de Suplementar',
 36212: 'Ag√™ncia Nacional de Vigil√¢ncia Sanit√°ria',
 36208: 'Hospital Cristo Redentor S.A.',
 36209: 'Hospital F√™mina S.A.',
 41000: 'Minist√©rio das Comunica√ß√µes - Unidades com v√≠nculo direto',
 20415: 'Empresa Brasil de Comunica√ß√£o',
 41231: 'Ag√™ncial Nacional de Telecomunica√ß√µes',
 41232: 'Fundo de Universaliza√ß√£o dos Servi√ßos de Telecomunica√ß√µes',
 41903: 'Fundo para o Desenvolvimento Tecnol√≥gico das Telecomunica√ß√µes',
 64902: 'Fundo Nacional do Idoso',
 64901: 'Fundo Nacional para a Crian√ßa e o Adolescente',
 35000: 'Minist√©rio das Rela√ß√µes Exteriores - Unidades com v√≠nculo direto',
 35201: 'Funda√ß√£o Alexandre de Gusm√£o',
 20303: 'Ind√∫strias Nucleares do Brasil',
 29208: 'Companhia de Pesquisa de Recursos Minerais',
 32000: 'Minist√©rio de Minas e Energia - Unidades com v√≠nculo direto',
 32205: 'Ag√™ncia Nacional do Petr√≥leo, G√°s Natural e Biocombust√≠veis',
 32263: 'Departamento Nacional de Produ√ß√£o Mineral',
 32210: 'Ag√™ncia Nacional de Energia El√©trica',
 32314: 'Empresa de Pesquisa Energ√©tica',
 20302: 'Nuclebr√°s Equipamentos Pesados S.A.',
 49000: 'Minist√©rio do Desenvolvimento Agr√°rio - Unidades com v√≠nculo direto',
 29205: 'Empresa de Trens Urbanos de Porto Alegre',
 29214: 'Companhia Brasileira de Trens Urbanos',
 53902: 'Fundo Constitucional de Financiamento do Centro-Oeste',
 53901: 'Fundo Constitucional de Financiamento do Norte',
 53903: 'Fundo Constitucional de Financiamento do Nordeste',
 22204: 'Departamento Nacional de Obras Contra as Secas',
 22203: 'Companhia de Desenvolvimento dos Vales do S√£o Francisco e do Parna√≠ba',
 53000: 'Minist√©rio do Desenvolvimento Regional - Unidades com v√≠nculo direto',
 53202: 'Superintend√™ncia do Desenvolvimento da Amaz√¥nia',
 74917: 'Fundo de Desenvolvimento da Amaz√¥nia',
 56902: 'Fundo Nacional de Habita√ß√£o de Interesse Social',
 53203: 'Superintend√™ncia do Desenvolvimento do Nordeste',
 44205: 'Ag√™ncia Nacional de √Åguas',
 53205: 'Ag√™ncia de Desenvolvimento da Amaz√¥nia',
 53207: 'Superintend√™ncia de Desenvolvimento do Centro-Oeste',
 74918: 'Fundo de Desenvolvimento do Nordeste',
 91214: 'Autoridade P√∫blica Ol√≠mpica',
 44206: 'Instituto de Pesquisas Jardim Bot√¢nico do Rio de Janeiro',
 44000: 'Minist√©rio do Meio Ambiente - Unidades com v√≠nculo direto',
 44902: 'Fundo Nacional sobre Mudan√ßa no Clima',
 20701: 'Instituto Brasileiro do Meio Ambiente e dos Recursos Naturais Renov√°veis',
 44207: 'Instituto Chico Mendes de Conserva√ß√£o da Biodiversidade',
 44204: 'Fundo Nacional do Meio Ambiente',
 38000: 'Minist√©rio do Trabalho e Emprego - Unidades com v√≠nculo direto',
 20403: 'Funda√ß√£o Casa de Rui Barbosa',
 20604: 'Instituto Brasileiro de Turismo',
 42207: 'Instituto Brasileiro de Museus',
 20411: 'Instituto do Patrim√¥nio Hist√≥rico e Art√≠stico Nacional',
 20412: 'Funda√ß√£o Nacional de Artes',
 34902: 'Fundo Nacional de Cultura',
 20203: 'Ag√™ncia Nacional do Cinema',
 54000: 'Minist√©rio do Turismo - Unidades com v√≠nculo direto',
 20408: 'Funda√ß√£o Cultural Palmares',
 20404: 'Funda√ß√£o Biblioteca Nacional',
 54901: 'Fundo Geral de Turismo',
 20101: 'Presid√™ncia da Rep√∫blica',
 67000: 'Secretaria de Pol√≠ticas de Promo√ß√£o da Igualdade Racial',
 64000: 'Secretaria de Direitos Humanos',
 69000: 'Secretaria da Micro e Pequena Empresa',
 20116: 'Fundo de Imprensa Nacional',
 24208: 'Instituto Nacional de Tecnologia da Informa√ß√£o',
 60000: 'Gabinete da Vice-Presid√™ncia da Rep√∫blica',
 20117: 'Fundo Nacional Antidrogas',
 61000: 'Secretaria de Assuntos Estrat√©gicos',
 52233: 'Amaz√¥nia Azul Tecnologia de Defesa S.A.',
 37904: 'Fundo do Regime Geral da Previd√™ncia Social',
 26449: 'Universidade Federal do Cariri',
 26448: 'Universidade Federal do Sul e Sudeste do Par√°',
 90000: 'Reserva de Conting√™ncia',
 26447: 'Universidade Federal do Oeste da Bahia',
 26450: 'Universidade Federal do Sul da Bahia',
 29201: 'Departamento Nacional de Estradas de Rodagem',
 74919: 'Fundo de Desenvolvimento do Centro-Oeste',
 20605: 'Companhia de Desenvolvimento de Barcarena',
 37000: 'Controladoria-Geral da Uni√£o - Unidades com v√≠nculo direto',
 20129: 'Secretaria Especial de Agricultura Familiar e do Desenvolvimento Agr√°rio',
 30914: 'Fundo Nacional do Idoso',
 30913: 'Fundo Nacional para a Crian√ßa e o Adolescente',
 81000: 'Minist√©rio da Mulher, Fam√≠lia e Direitos Humanos - Unidades com v√≠nculo direto',
 32396: 'Ag√™ncia Nacional de Minera√ß√£o',
 26456: 'UNIVERSIDADE FEDERAL DO AGRESTE DE PERNAMBUCO',
 26455: 'UNIVERSIDADE FEDERAL DO DELTA DO PARNAIBA',
 24216: 'TELECOMUNICACOES BRASILEIRAS S/A',
 26453: 'UNIVERSIDADE FEDERAL DE JATAI',
 26454: 'UNIVERSIDADE FEDERAL DE RONDONOPOLIS',
 26457: 'UNIVERSIDADE FEDERAL DO NORTE DE TOCANTINS',
 26452: 'UNIVERSIDADE FEDERAL DE CATALAO'}

In [67]:
dfs_concatenados['nome_orgao'] = dfs_concatenados['nome_orgao'].fillna(
    dfs_concatenados['codigo_orgao'].map(diccionario_codigo_nome)
)

condicion = dfs_concatenados['codigo_orgao'] == codigos_orgao[3]
dfs_concatenados[condicion]

      codigo_orgao_superior  ... ano_exercicio
21                    22000  ...          2013
24                    22000  ...          2013
27                    22000  ...          2013
35                    22000  ...          2013
38                    22000  ...          2013
...                     ...  ...           ...
5573                  22000  ...          2021
5574                  22000  ...          2021
5580                  22000  ...          2021
5581                  22000  ...          2021
5582                  22000  ...          2021

[8418 rows x 16 columns]

### Convertimos los valores a tipo int

In [68]:
dfs_concatenados.head()

   codigo_orgao_superior  ... ano_exercicio
0                  63000  ...          2013
1                  63000  ...          2013
2                  63000  ...          2013
3                  63000  ...          2013
4                  63000  ...          2013

[5 rows x 16 columns]

In [69]:
dfs_concatenados['valor_lancado'].dtypes

dtype('O')

In [70]:
dfs_concatenados['valor_previsto_atualizado'] = dfs_concatenados['valor_previsto_atualizado'].str.replace(',','.')
dfs_concatenados['valor_previsto_atualizado'] = dfs_concatenados['valor_previsto_atualizado'].astype(float)

dfs_concatenados['valor_lancado'] = dfs_concatenados['valor_lancado'].str.replace(',','.')
dfs_concatenados['valor_lancado'] = dfs_concatenados['valor_lancado'].astype(float)

dfs_concatenados['valor_realizado'] = dfs_concatenados['valor_realizado'].str.replace(',','.')
dfs_concatenados['valor_realizado'] = dfs_concatenados['valor_realizado'].astype(float)

In [71]:
dfs_concatenados.groupby(['ano_exercicio'])[['valor_previsto_atualizado','valor_lancado', 'valor_realizado']].sum()

               valor_previsto_atualizado  valor_lancado  valor_realizado
ano_exercicio
2013                        2.128724e+12   1.137824e+12     1.663430e+12
2014                        2.333104e+12   1.258080e+12     2.211514e+12
2015                        2.871164e+12   3.063356e+11     2.634219e+12
2016                        2.910191e+12   3.314445e+11     2.787181e+12
2017                        3.400684e+12   4.535271e+11     2.476074e+12
2018                        3.476635e+12   4.686850e+11     2.865977e+12
2019                        3.249178e+12   3.395478e+11     2.880424e+12
2020                        3.528192e+12   6.238020e+11     3.460501e+12
2021                        4.043359e+12   3.569096e+11     3.679059e+12

In [72]:
porcentaje_nulos = sup_df.mostrar_porcentaje_nulos(dfs_concatenados)
porcentaje_nulos

                      Columna  Porcentaje Nulos
10  valor_previsto_atualizado          5.000005
12            valor_realizado          3.845371
7              origem_receita          3.743354
4      codigo_unidade_gestora          3.272048
8             especie_receita          3.110887
9                detalhamento          2.858524
11              valor_lancado          2.574201
13       percentual_realizado          2.351556
14            data_lancamento          2.322033
5        nome_unidade_gestora          1.898180
6         categoria_economica          1.849169
3                  nome_orgao          0.000000
0       codigo_orgao_superior          0.000000
1         nome_orgao_superior          0.000000
2                codigo_orgao          0.000000
15              ano_exercicio          0.000000

In [73]:
dfs_concatenados.shape

(1026299, 16)

In [74]:
dfs_concatenados.isnull().sum()

codigo_orgao_superior            0
nome_orgao_superior              0
codigo_orgao                     0
nome_orgao                       0
codigo_unidade_gestora       33581
nome_unidade_gestora         19481
categoria_economica          18978
origem_receita               38418
especie_receita              31927
detalhamento                 29337
valor_previsto_atualizado    51315
valor_lancado                26419
valor_realizado              39465
percentual_realizado         24134
data_lancamento              23831
ano_exercicio                    0
dtype: int64

## eliminamos los duplicados y exportamos el dataframe con los datos mas o menos limpios.

In [75]:
dfs_concatenados.drop_duplicates(inplace=True)

In [76]:
dfs_concatenados.to_csv('../datos/tratados/dfs_concatenados.csv')